import { randomUUID } from 'node:crypto'
import DOMPurify from 'isomorphic-dompurify'

/**
 * Server-side validation + sanitization for customer personalization uploads.
 *
 * Security model (see personalization-plan.md "Bezpieczeństwo uploadu plików"): the file
 * type is decided from the *content* (magic bytes / XML sniff), never the client-declared
 * Content-Type or extension. SVGs — the only active-content format we accept — are parsed
 * and sanitized (DOMPurify, SVG profile) with hostile constructs rejected outright. The
 * stored filename is generated by us (uuid + extension from the detected type), which kills
 * path traversal, double extensions, and null-byte tricks. Combined with serving from the
 * separate R2 origin as `Content-Disposition: attachment`, a hostile upload can't execute
 * in the store/admin context.
 */

export type DetectedType = {
  mime: 'image/png' | 'image/jpeg' | 'image/svg+xml' | 'application/pdf'
  ext: 'png' | 'jpg' | 'svg' | 'pdf'
}

export type ValidationOk = {
  ok: true
  mime: DetectedType['mime']
  filename: string
  bytes: Buffer
  sanitized: boolean
}
export type ValidationErr = { ok: false; error: string }
export type ValidationResult = ValidationOk | ValidationErr

// Absolute ceiling regardless of the per-option maxSizeMB, as a backstop against
// a misconfigured option or oversized abuse.
export const HARD_MAX_BYTES = 25 * 1024 * 1024

const PNG_SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
const JPEG_SIG = Buffer.from([0xff, 0xd8, 0xff])
const PDF_SIG = Buffer.from('%PDF-', 'ascii')

/** Sniff the real type from leading bytes / XML structure. Null when unrecognized. */
export function detectType(buf: Buffer): DetectedType | null {
  if (buf.length >= PNG_SIG.length && buf.subarray(0, PNG_SIG.length).equals(PNG_SIG)) {
    return { mime: 'image/png', ext: 'png' }
  }
  if (buf.length >= JPEG_SIG.length && buf.subarray(0, JPEG_SIG.length).equals(JPEG_SIG)) {
    return { mime: 'image/jpeg', ext: 'jpg' }
  }
  if (buf.length >= PDF_SIG.length && buf.subarray(0, PDF_SIG.length).equals(PDF_SIG)) {
    return { mime: 'application/pdf', ext: 'pdf' }
  }
  // SVG has no binary magic bytes — sniff the XML. Skip a UTF-8 BOM + leading whitespace,
  // then require an XML prolog or an <svg root within the first chunk.
  const head = buf.subarray(0, 1024).toString('utf8').replace(/^﻿/, '').trimStart()
  if (/^<\?xml[\s>]/i.test(head) || /^<!DOCTYPE\s+svg/i.test(head) || /^<svg[\s>]/i.test(head)) {
    if (/<svg[\s>]/i.test(buf.toString('utf8').slice(0, 65536))) {
      return { mime: 'image/svg+xml', ext: 'svg' }
    }
  }
  return null
}

// Hostile constructs that must never survive in a stored SVG. We reject (rather than
// silently strip) so a flagged upload is visible, and as a tripwire if DOMPurify ever
// regresses. External entities / DOCTYPE guard against XXE; the rest against active content.
const SVG_FORBIDDEN: Array<{ re: RegExp; what: string }> = [
  { re: /<!DOCTYPE/i, what: 'DOCTYPE' },
  { re: /<!ENTITY/i, what: 'entity declaration' },
  { re: /<script[\s>]/i, what: '<script>' },
  { re: /<foreignObject[\s>]/i, what: '<foreignObject>' },
  { re: /\son\w+\s*=/i, what: 'event handler attribute' },
  { re: /javascript:/i, what: 'javascript: URI' },
  { re: /<iframe[\s>]/i, what: '<iframe>' },
  { re: /<embed[\s>]/i, what: '<embed>' },
  { re: /<use[^>]+href\s*=\s*["']?https?:/i, what: 'external <use> reference' },
]

/**
 * Validate an SVG: reject obvious hostile content, then run it through DOMPurify (SVG
 * profile) so the *stored* bytes are the sanitized version. We keep it a vector (the owner
 * needs it for engraving) rather than rasterizing.
 */
function sanitizeSvg(buf: Buffer): { ok: true; bytes: Buffer } | ValidationErr {
  const source = buf.toString('utf8')
  for (const { re, what } of SVG_FORBIDDEN) {
    if (re.test(source)) {
      return { ok: false, error: `SVG contains disallowed content (${what}). Please upload a clean export.` }
    }
  }
  const clean = DOMPurify.sanitize(source, {
    USE_PROFILES: { svg: true, svgFilters: true },
    // Defense in depth — these are already rejected above, but make DOMPurify drop them too.
    FORBID_TAGS: ['script', 'foreignObject', 'iframe', 'embed'],
    FORBID_ATTR: ['onload', 'onerror', 'onclick'],
  })
  if (!clean || !/<svg[\s>]/i.test(clean)) {
    return { ok: false, error: 'SVG could not be processed. Please upload a different file.' }
  }
  return { ok: true, bytes: Buffer.from(clean, 'utf8') }
}

/**
 * Full validation pipeline for one uploaded file. `allowedTypes` is the option's configured
 * MIME allow-list; `maxBytes` the option's maxSizeMB (already converted), clamped to the
 * hard global cap by the caller. Returns sanitized bytes + a generated filename on success.
 */
export function validateUpload(
  buf: Buffer,
  allowedTypes: string[],
  maxBytes: number,
): ValidationResult {
  if (buf.length === 0) return { ok: false, error: 'The file is empty.' }
  if (buf.length > maxBytes) {
    return { ok: false, error: `File is too large (max ${Math.floor(maxBytes / (1024 * 1024))} MB).` }
  }

  const detected = detectType(buf)
  if (!detected) {
    return { ok: false, error: 'Unsupported or unrecognized file type.' }
  }
  if (!allowedTypes.includes(detected.mime)) {
    return { ok: false, error: 'This file type is not accepted for this option.' }
  }

  let bytes = buf
  let sanitized = false
  if (detected.mime === 'image/svg+xml') {
    const result = sanitizeSvg(buf)
    if (!result.ok) return result
    bytes = result.bytes
    sanitized = true
  }

  return {
    ok: true,
    mime: detected.mime,
    filename: `${randomUUID()}.${detected.ext}`,
    bytes,
    sanitized,
  }
}
