/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    pages: Page;
    'contact-messages': ContactMessage;
    'stock-alerts': StockAlert;
    'newsletter-subscribers': NewsletterSubscriber;
    collections: Collection;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'stock-alerts': StockAlertsSelect<false> | StockAlertsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL-safe identifier, e.g. "pcb-coasters"
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional parent category for nesting
   */
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL-safe identifier, e.g. "copper-circuit-coaster"
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Price in minor units (e.g. 4900 = 49.00 PLN/EUR/USD)
   */
  price: number;
  /**
   * Optional crossed-out reference price (minor units)
   */
  compareAtPrice?: number | null;
  material: 'pcb' | 'wood' | 'other';
  /**
   * Show "New" badge on product card and PDP
   */
  isNew?: boolean | null;
  /**
   * Show "Bestseller" badge
   */
  isBestseller?: boolean | null;
  variants?:
    | {
        name: string;
        sku: string;
        stock: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Sum of all variant stocks (auto-calculated)
   */
  totalStock?: number | null;
  /**
   * Net product weight in grams (for shipping estimation)
   */
  weightGrams?: number | null;
  /**
   * Physical dimensions in millimeters
   */
  dimensions?: {
    widthMm?: number | null;
    heightMm?: number | null;
    depthMm?: number | null;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  status: 'draft' | 'active' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  stripePaymentIntentId: string;
  status: 'pending' | 'paid' | 'fulfilled' | 'shipped' | 'cancelled';
  customer: {
    email: string;
    name: string;
    address: {
      line1: string;
      line2?: string | null;
      city: string;
      postalCode: string;
      country: string;
    };
  };
  customerEmailDenorm?: string | null;
  items?:
    | {
        product: number | Product;
        /**
         * SKU of the purchased variant, if applicable
         */
        variantSku?: string | null;
        quantity: number;
        /**
         * Snapshot of price (minor units) at the time of purchase
         */
        priceAtPurchase: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Shipping amount charged (minor units), already included in totalAtPurchase
   */
  shippingCost?: number | null;
  /**
   * Name of the shipping zone applied at checkout
   */
  shippingZone?: string | null;
  /**
   * Total amount paid (minor units), incl. shipping
   */
  totalAtPurchase: number;
  /**
   * ISO 4217 currency code
   */
  currency: string;
  /**
   * Carrier tracking number, set when shipped
   */
  shippingTracking?: string | null;
  /**
   * VAT/sales tax included in totalAtPurchase (minor units)
   */
  taxAmount?: number | null;
  /**
   * Tax ID provided by customer at checkout (B2B reverse charge, etc.)
   */
  customerVatId?: string | null;
  /**
   * Stripe promotion code applied at checkout, if any
   */
  promoCode?: string | null;
  /**
   * Total discount applied (minor units), if any
   */
  discountAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "about", "shipping-returns", "faq"
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted through the public contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  /**
   * IP captured at submission (for abuse review)
   */
  ip?: string | null;
  userAgent?: string | null;
  /**
   * Mark when responded to / archived
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email subscriptions for back-in-stock notifications on out-of-stock variants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-alerts".
 */
export interface StockAlert {
  id: number;
  product: number | Product;
  /**
   * Cached from product at signup time
   */
  productSlug?: string | null;
  variantSku: string;
  email: string;
  /**
   * Set automatically when restock email is sent
   */
  notified?: boolean | null;
  notifiedAt?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email subscribers for newsletter / new product announcements. Export from here to your email tool.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  source?: ('footer' | 'checkout' | 'manual') | null;
  unsubscribed?: boolean | null;
  /**
   * Timestamp when GDPR consent was given
   */
  consentedAt?: string | null;
  /**
   * Exact consent wording shown at signup (snapshot for legal evidence)
   */
  consentText?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Curated design themes (Botanical, Sport, Abstract, Regional). Each entry becomes a /collections/[slug] landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  slug: string;
  /**
   * Short kicker shown above title on landing page (e.g. "Collection 01")
   */
  subtitle?: string | null;
  /**
   * One-line emotional hook shown under title
   */
  tagline?: string | null;
  /**
   * Long-form intro shown above product grid on the collection page
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hero visual for collection landing page
   */
  heroImage?: (number | null) | Media;
  /**
   * Products belonging to this collection (manually curated)
   */
  products?: (number | Product)[] | null;
  /**
   * Sort order on /collections index (lower = first)
   */
  order?: number | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * URL redirects (site-relative paths, e.g. /products/old -> /products/new). Auto-created on slug changes; editable by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Source path to redirect from, e.g. /products/old-slug
   */
  from: string;
  /**
   * Destination path, e.g. /products/new-slug
   */
  to: string;
  /**
   * On = permanent (308/301), off = temporary (307/302). Keep on for slug changes so search engines update.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'stock-alerts';
        value: number | StockAlert;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  price?: T;
  compareAtPrice?: T;
  material?: T;
  isNew?: T;
  isBestseller?: T;
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        stock?: T;
        id?: T;
      };
  totalStock?: T;
  weightGrams?: T;
  dimensions?:
    | T
    | {
        widthMm?: T;
        heightMm?: T;
        depthMm?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  stripePaymentIntentId?: T;
  status?: T;
  customer?:
    | T
    | {
        email?: T;
        name?: T;
        address?:
          | T
          | {
              line1?: T;
              line2?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
      };
  customerEmailDenorm?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        quantity?: T;
        priceAtPurchase?: T;
        id?: T;
      };
  shippingCost?: T;
  shippingZone?: T;
  totalAtPurchase?: T;
  currency?: T;
  shippingTracking?: T;
  taxAmount?: T;
  customerVatId?: T;
  promoCode?: T;
  discountAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  ip?: T;
  userAgent?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-alerts_select".
 */
export interface StockAlertsSelect<T extends boolean = true> {
  product?: T;
  productSlug?: T;
  variantSku?: T;
  email?: T;
  notified?: T;
  notifiedAt?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  unsubscribed?: T;
  consentedAt?: T;
  consentText?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  tagline?: T;
  description?: T;
  heroImage?: T;
  products?: T;
  order?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  storeName: string;
  storeEmail: string;
  shippingZones?:
    | {
        /**
         * e.g. "Poland", "EU", "Worldwide"
         */
        name: string;
        /**
         * Comma-separated ISO country codes, or "*" for all
         */
        countries: string;
        /**
         * Flat shipping price (minor units)
         */
        flatRate: number;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'etsy' | 'pinterest' | 'x' | 'tiktok' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  announcementBar?: {
    enabled?: boolean | null;
    message?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  storeName?: T;
  storeEmail?: T;
  shippingZones?:
    | T
    | {
        name?: T;
        countries?: T;
        flatRate?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}